osx_image: xcode7.3
language: objective-c
script: xcodebuild -workspace Example/TPSDropDown.xcworkspace -scheme TPSDropDown-Example -sdk iphonesimulator -destination 'name=iPhone 6' build test | xcpretty -c && exit ${PIPESTATUS[0]}
